name: CI

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]
    
  workflow_dispatch:
  
jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install dependencies
        run: npm install

  test_and_analyze:
    name: Run tests
    runs-on: ubuntu-latest
    needs: install  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      
      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Run ESlint
        run: npm run eslint'
        
      - name: Run Tests
        run: npm test:ci